ruby '2.2.2'

source 'https://rubygems.org'

gem 'rails', '4.2.1'
gem 'pg'
gem 'jbuilder', '~> 2.0'

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem "factory_girl_rails"
  gem "pry-rails"
  gem "rspec-rails", "~> 3.0.0"
  gem "spring-commands-rspec"
end

group :test do
  gem "shoulda-matchers", require: false
end

